#!/bin/bash

function runserver {
    ./elasticsearch/bin/service/elasticsearch start
    cd $1
    pwd
    echo "yes" | python manage.py collectstatic
    python manage.py validate
    python manage.py syncdb
    python manage.py evolve --hint
    python manage.py evolve --hint --execute
    
    python manage.py runserver
}

runserver cc


